
version: '3.1'
services:
  postgres:
    image: postgres:12.4
    ports: 
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: soloquella
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: redis:6
    ports:
      - 6379:6379
