version: '3.1'
services:
  redis:
    container_name: redis
    build: 
      context: ./images/redis
    image: redis-custom
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
